# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml


# We'll be using the IBM Cloud registry
docker-registry:
  enabled: false

jenkins-x-platform:
  PipelineSecrets:

    # lets enable IBM Cloud Container Registry (icr) docker builds
    DockerConfig: |-
      {
          "credHelpers": {
              "default-icr-io": "icr",
              "default-us-icr-io": "icr",
              "default-de-icr-io": "icr",
              "default-uk-icr-io": "icr",
              "default-au-icr-io": "icr",
              "default-jp-icr-io": "icr"
          }
      }